# Generated by Django 4.0.2 on 2022-03-02 18:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=tinymce.models.HTMLField(blank=True, max_length=200000, null=True),
        ),
    ]
